# Automatically generated by configure - do not modify

all:
SRC_PATH=/Users/chrisbridges/Work/RTS_Demo/qemu
TARGET_DIRS=aarch64-softmmu alpha-softmmu arm-softmmu avr-softmmu hppa-softmmu i386-softmmu loongarch64-softmmu m68k-softmmu microblaze-softmmu microblazeel-softmmu mips-softmmu mips64-softmmu mips64el-softmmu mipsel-softmmu or1k-softmmu ppc-softmmu ppc64-softmmu riscv32-softmmu riscv64-softmmu rx-softmmu s390x-softmmu sh4-softmmu sh4eb-softmmu sparc-softmmu sparc64-softmmu tricore-softmmu x86_64-softmmu xtensa-softmmu xtensaeb-softmmu
GDB=
SUBDIRS= contrib/plugins
PYTHON=/Users/chrisbridges/Work/RTS_Demo/qemu/build/pyvenv/bin/python3 -B
MKVENV_ENSUREGROUP=/Users/chrisbridges/Work/RTS_Demo/qemu/build/pyvenv/bin/python3 -B /Users/chrisbridges/Work/RTS_Demo/qemu/python/scripts/mkvenv.py ensuregroup  --online
GENISOIMAGE=
MESON=/Users/chrisbridges/Work/RTS_Demo/qemu/build/pyvenv/bin/meson
NINJA=/Users/chrisbridges/miniconda3/envs/py310_rts/bin/ninja
EXESUF=
CONFIG_DEFAULT_TARGETS=y
TCG_TESTS_TARGETS=
