/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * Schema-defined QAPI types
 *
 * Copyright IBM, Corp. 2011
 * Copyright (c) 2013-2018 Red Hat Inc.
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#ifndef QAPI_TYPES_MACHINE_COMMON_H
#define QAPI_TYPES_MACHINE_COMMON_H

#include "qapi/qapi-builtin-types.h"

typedef enum S390CpuEntitlement {
    S390_CPU_ENTITLEMENT_AUTO,
    S390_CPU_ENTITLEMENT_LOW,
    S390_CPU_ENTITLEMENT_MEDIUM,
    S390_CPU_ENTITLEMENT_HIGH,
    S390_CPU_ENTITLEMENT__MAX,
} S390CpuEntitlement;

#define S390CpuEntitlement_str(val) \
    qapi_enum_lookup(&S390CpuEntitlement_lookup, (val))

extern const QEnumLookup S390CpuEntitlement_lookup;

#endif /* QAPI_TYPES_MACHINE_COMMON_H */
